<table class=" table table-hover table-bordered">

    <tr>
        <td>老板姓名</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>老板手机</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>习惯和喜欢的方式</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>照片</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>生日</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>老家哪里</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>文化水平</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>个人喜好</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>个人忌讳</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>饮食偏好</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>行业口碑</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>家族生意圈/生意朋友圈</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>发展履历</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>家族背景（突出创一代OR 二代）</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>家庭结构</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>最适合联络时间</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>投资相关产业</td>
        <td>xxx</td>
    </tr>
    <tr>
        <td>宗教信仰</td>
        <td>xxx</td>
    </tr>
</table>